# SPDX-FileCopyrightText: 2026 Meowdia Community
# SPDX-License-Identifier: MIT OR Apache-2.0

version = 1

[[annotations]]
path = [
    "Cargo.lock",
    "flake.lock",
]
SPDX-FileCopyrightText = "2026 Meowdia Community"
SPDX-License-Identifier = "MIT OR Apache-2.0"

[[annotations]]
path = ["iana/snapshots/*.xml"]
precedence = "override"
SPDX-FileCopyrightText = ["IANA", "IETF Trust"]
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileComment = "Snapshot of IANA protocol registry data."
